# Generated by Django 3.0.7 on 2020-06-30 22:05

import aldryn_apphooks_config.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('djangocms_blog', '0039_auto_20200331_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=False, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserSeenPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_blog.Post')),
            ],
            options={
                'verbose_name': 'View Count',
                'verbose_name_plural': 'View Count',
            },
        ),
        migrations.CreateModel(
            name='PopularPostsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_blog_popularpostsplugin', serialize=False, to='cms.CMSPlugin')),
                ('current_site', models.BooleanField(default=True, help_text='Select items from the current site only', verbose_name='current site')),
                ('template_folder', models.CharField(choices=[('plugins', 'Default template')], default='plugins', help_text='Select plugin template to load for this instance', max_length=200, verbose_name='Plugin template')),
                ('popular_posts', models.IntegerField(default=5, help_text='The number of latests articles to be displayed.', verbose_name='articles')),
                ('app_config', aldryn_apphooks_config.fields.AppHookConfigField(blank=True, help_text='When selecting a value, the form is reloaded to get the updated default', null=True, on_delete=django.db.models.deletion.CASCADE, to='djangocms_blog.BlogConfig', verbose_name='app. config')),
                ('categories', models.ManyToManyField(blank=True, help_text='Show only the blog articles tagged with chosen categories.', to='djangocms_blog.BlogCategory', verbose_name='filter by category')),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Show only the blog articles tagged with chosen tags.', related_name='djangocms_blog_latest_post_2', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='filter by tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
