# Generated by Django 3.0.7 on 2020-06-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0040_auto_20200630_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularpostsplugin',
            name='template_folder',
            field=models.CharField(choices=[('plugins', 'Default template'), ('timeline', 'Vertical timeline'), ('masonry', 'Masonry style')], default='plugins', help_text='Select plugin template to load for this instance', max_length=200, verbose_name='Plugin template'),
        ),
    ]
